# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Set the base image for the virtual machine
  config.vm.box = "bento/ubuntu-22.04"

  # Sync folders between the host and the guest in case of further development and transfer of server saves
  # config.vm.synced_folder ".", "/vagrant"

  # Configure port forwarding
  config.vm.network "forwarded_port", guest: 8211, host: 8211
  config.vm.network "forwarded_port", guest: 25575, host: 25575

  # Network configuration
  config.vm.network "public_network", ip: "192.168.1.200"

  # Virtual machine configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.name = "Server_pal"
  end

  # Provisioning the virtual machine
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Update the package list
    sudo apt-get update -y

    # Install packages
    sudo apt-get install -y software-properties-common lib32gcc-s1

    # Add repositories
    sudo add-apt-repository multiverse

    # Unpack i386
    sudo dpkg --add-architecture i386

    # Update the package list
    sudo apt-get update -y
    
    # Add user agreement
    echo steam steam/question select "I AGREE" | sudo debconf-set-selections
    echo steam steam/license note '' | sudo debconf-set-selections

    # Install packages
    sudo apt-get install -y steam steamcmd screen

    # Create steam user
    sudo useradd -m steam

    # Add the path to the games to the PATH variable
    echo 'export PATH="/usr/games/:$PATH"' >> /home/steam/.bashrc

    # Install steamworks
    sudo -u steam steamcmd +force_install_dir '/home/steam/Steam/steamapps/common/steamworks' +login anonymous +app_update 1007 +quit

    # Run steamcmd to install PalServer
    sudo -u steam steamcmd +force_install_dir '/home/steam/Steam/steamapps/common/PalServer' +login anonymous +app_update 2394010 validate +quit

    # Create a directory for steamclient.so
    sudo -u steam mkdir -p /home/steam/.steam/sdk64

    # Copy steamclient.so to the necessary directory
    sudo -u steam cp '/home/steam/Steam/steamapps/common/steamworks/linux64/steamclient.so' /home/steam/.steam/sdk64/

    # Add auto-update to cron
    (crontab -l 2>/dev/null; echo "0 * * * * steamcmd +force_install_dir \"${PAL_SERVER_DIR}\" +login anonymous +app_update 2394010 validate +quit") | crontab -

    # Start the server
    sudo -u steam screen -dmS palserver /home/steam/Steam/steamapps/common/PalServer/PalServer.sh
  SHELL
end
